export const themes = [
  {
    id: 'animals',
    name: 'Animals',
    icon: '🐾',
    color: '#FF7043',
    bgColor: '#FBE9E7',
    words: [
      { id: 'cat', name: 'cat', emoji: '🐱' },
      { id: 'dog', name: 'dog', emoji: '🐶' },
      { id: 'bird', name: 'bird', emoji: '🐦' },
      { id: 'fish', name: 'fish', emoji: '🐟' },
      { id: 'cow', name: 'cow', emoji: '🐄' },
      { id: 'horse', name: 'horse', emoji: '🐴' },
      { id: 'elephant', name: 'elephant', emoji: '🐘' },
      { id: 'lion', name: 'lion', emoji: '🦁' },
      { id: 'monkey', name: 'monkey', emoji: '🐵' },
      { id: 'rabbit', name: 'rabbit', emoji: '🐰' },
      { id: 'frog', name: 'frog', emoji: '🐸' },
      { id: 'duck', name: 'duck', emoji: '🦆' },
      { id: 'tiger', name: 'tiger', emoji: '🐯' },
      { id: 'penguin', name: 'penguin', emoji: '🐧' },
      { id: 'crocodile', name: 'crocodile', emoji: '🐊' },
      { id: 'giraffe', name: 'giraffe', emoji: '🦒' },
      { id: 'bear', name: 'bear', emoji: '🐻' },
      { id: 'wolf', name: 'wolf', emoji: '🐺' },
      { id: 'sheep', name: 'sheep', emoji: '🐑' },
      { id: 'pig', name: 'pig', emoji: '🐷' },
    ],
  },
  {
    id: 'fruits',
    name: 'Fruits',
    icon: '🍎',
    color: '#66BB6A',
    bgColor: '#E8F5E9',
    words: [
      { id: 'apple', name: 'apple', emoji: '🍎' },
      { id: 'banana', name: 'banana', emoji: '🍌' },
      { id: 'orange', name: 'orange', emoji: '🍊' },
      { id: 'grape', name: 'grape', emoji: '🍇' },
      { id: 'strawberry', name: 'strawberry', emoji: '🍓' },
      { id: 'watermelon', name: 'watermelon', emoji: '🍉' },
      { id: 'pear', name: 'pear', emoji: '🍐' },
      { id: 'cherry', name: 'cherry', emoji: '🍒' },
      { id: 'peach', name: 'peach', emoji: '🍑' },
      { id: 'lemon', name: 'lemon', emoji: '🍋' },
      { id: 'mango', name: 'mango', emoji: '🥭' },
      { id: 'pineapple', name: 'pineapple', emoji: '🍍' },
      { id: 'coconut', name: 'coconut', emoji: '🥥' },
      { id: 'kiwi', name: 'kiwi', emoji: '🥝' },
      { id: 'plum', name: 'plum', emoji: '🍑' },
      { id: 'blueberry', name: 'blueberry', emoji: '🫐' },
      { id: 'lime', name: 'lime', emoji: '🍋' },
      { id: 'melon', name: 'melon', emoji: '🍈' },
      { id: 'fig', name: 'fig', emoji: '🍇' },
      { id: 'pomegranate', name: 'pomegranate', emoji: '❤️' },
    ],
  },
  {
    id: 'vehicles',
    name: 'Vehicles',
    icon: '🚗',
    color: '#42A5F5',
    bgColor: '#E3F2FD',
    words: [
      { id: 'car', name: 'car', emoji: '🚗' },
      { id: 'bus', name: 'bus', emoji: '🚌' },
      { id: 'train', name: 'train', emoji: '🚆' },
      { id: 'airplane', name: 'airplane', emoji: '✈️' },
      { id: 'boat', name: 'boat', emoji: '⛵' },
      { id: 'bicycle', name: 'bicycle', emoji: '🚲' },
      { id: 'truck', name: 'truck', emoji: '🚚' },
      { id: 'motorcycle', name: 'motorcycle', emoji: '🏍️' },
      { id: 'helicopter', name: 'helicopter', emoji: '🚁' },
      { id: 'rocket', name: 'rocket', emoji: '🚀' },
      { id: 'tractor', name: 'tractor', emoji: '🚜' },
      { id: 'ambulance', name: 'ambulance', emoji: '🚑' },
      { id: 'submarine', name: 'submarine', emoji: '🚢' },
      { id: 'scooter', name: 'scooter', emoji: '🛵' },
      { id: 'taxi', name: 'taxi', emoji: '🚕' },
      { id: 'firetruck', name: 'fire truck', emoji: '🚒' },
      { id: 'canoe', name: 'canoe', emoji: '🛶' },
      { id: 'skateboard', name: 'skateboard', emoji: '🛹' },
      { id: 'balloon', name: 'hot air balloon', emoji: '🎈' },
      { id: 'spaceship', name: 'spaceship', emoji: '🛸' },
    ],
  },
  {
    id: 'food',
    name: 'Food',
    icon: '🍕',
    color: '#FFA726',
    bgColor: '#FFF3E0',
    words: [
      { id: 'pizza', name: 'pizza', emoji: '🍕' },
      { id: 'burger', name: 'burger', emoji: '🍔' },
      { id: 'icecream', name: 'ice cream', emoji: '🍦' },
      { id: 'cake', name: 'cake', emoji: '🎂' },
      { id: 'cookie', name: 'cookie', emoji: '🍪' },
      { id: 'donut', name: 'donut', emoji: '🍩' },
      { id: 'hotdog', name: 'hot dog', emoji: '🌭' },
      { id: 'taco', name: 'taco', emoji: '🌮' },
      { id: 'sushi', name: 'sushi', emoji: '🍣' },
      { id: 'popcorn', name: 'popcorn', emoji: '🍿' },
      { id: 'sandwich', name: 'sandwich', emoji: '🥪' },
      { id: 'pasta', name: 'pasta', emoji: '🍝' },
      { id: 'salad', name: 'salad', emoji: '🥗' },
      { id: 'soup', name: 'soup', emoji: '🍲' },
      { id: 'steak', name: 'steak', emoji: '🥩' },
      { id: 'eggs', name: 'eggs', emoji: '🍳' },
      { id: 'bread', name: 'bread', emoji: '🍞' },
      { id: 'cheese', name: 'cheese', emoji: '🧀' },
      { id: 'chocolate', name: 'chocolate', emoji: '🍫' },
      { id: 'pancakes', name: 'pancakes', emoji: '🥞' },
    ],
  },
  {
    id: 'nature',
    name: 'Nature',
    icon: '🌳',
    color: '#26A69A',
    bgColor: '#E0F2F1',
    words: [
      { id: 'tree', name: 'tree', emoji: '🌳' },
      { id: 'flower', name: 'flower', emoji: '🌸' },
      { id: 'sun', name: 'sun', emoji: '☀️' },
      { id: 'moon', name: 'moon', emoji: '🌙' },
      { id: 'star', name: 'star', emoji: '⭐' },
      { id: 'cloud', name: 'cloud', emoji: '☁️' },
      { id: 'rainbow', name: 'rainbow', emoji: '🌈' },
      { id: 'snowflake', name: 'snowflake', emoji: '❄️' },
      { id: 'mountain', name: 'mountain', emoji: '⛰️' },
      { id: 'volcano', name: 'volcano', emoji: '🌋' },
      { id: 'wave', name: 'wave', emoji: '🌊' },
      { id: 'leaf', name: 'leaf', emoji: '🍃' },
      { id: 'forest', name: 'forest', emoji: '🌲' },
      { id: 'river', name: 'river', emoji: '🏞️' },
      { id: 'desert', name: 'desert', emoji: '🏜️' },
      { id: 'waterfall', name: 'waterfall', emoji: '💦' },
      { id: 'lightning', name: 'lightning', emoji: '⚡' },
      { id: 'tornado', name: 'tornado', emoji: '🌪️' },
      { id: 'glacier', name: 'glacier', emoji: '🏔️' },
      { id: 'island', name: 'island', emoji: '🏝️' },
    ],
  },
  {
    id: 'sports',
    name: 'Sports',
    icon: '⚽',
    color: '#AB47BC',
    bgColor: '#F3E5F5',
    words: [
      { id: 'soccer', name: 'soccer', emoji: '⚽' },
      { id: 'basketball', name: 'basketball', emoji: '🏀' },
      { id: 'tennis', name: 'tennis', emoji: '🎾' },
      { id: 'baseball', name: 'baseball', emoji: '⚾' },
      { id: 'football', name: 'football', emoji: '🏈' },
      { id: 'volleyball', name: 'volleyball', emoji: '🏐' },
      { id: 'bowling', name: 'bowling', emoji: '🎳' },
      { id: 'golf', name: 'golf', emoji: '⛳' },
      { id: 'boxing', name: 'boxing', emoji: '🥊' },
      { id: 'swimming', name: 'swimming', emoji: '🏊' },
      { id: 'skiing', name: 'skiing', emoji: '⛷️' },
      { id: 'cycling', name: 'cycling', emoji: '🚴' },
      { id: 'archery', name: 'archery', emoji: '🏹' },
      { id: 'gymnastics', name: 'gymnastics', emoji: '🤸' },
      { id: 'surfing', name: 'surfing', emoji: '🏄' },
      { id: 'running', name: 'running', emoji: '🏃' },
      { id: 'weightlifting', name: 'weightlifting', emoji: '🏋️' },
      { id: 'yoga', name: 'yoga', emoji: '🧘' },
      { id: 'karate', name: 'karate', emoji: '🥋' },
      { id: 'horseriding', name: 'horse riding', emoji: '🏇' },
    ],
  },
  {
    id: 'clothes',
    name: 'Clothes',
    icon: '👕',
    color: '#EC407A',
    bgColor: '#FCE4EC',
    words: [
      { id: 'shirt', name: 'shirt', emoji: '👕' },
      { id: 'pants', name: 'pants', emoji: '👖' },
      { id: 'hat', name: 'hat', emoji: '🎩' },
      { id: 'shoe', name: 'shoe', emoji: '👟' },
      { id: 'dress', name: 'dress', emoji: '👗' },
      { id: 'glasses', name: 'glasses', emoji: '👓' },
      { id: 'glove', name: 'glove', emoji: '🧤' },
      { id: 'sock', name: 'sock', emoji: '🧦' },
      { id: 'scarf', name: 'scarf', emoji: '🧣' },
      { id: 'crown', name: 'crown', emoji: '👑' },
      { id: 'swimsuit', name: 'swimsuit', emoji: '👙' },
      { id: 'boot', name: 'boot', emoji: '🥾' },
      { id: 'tie', name: 'tie', emoji: '👔' },
      { id: 'bag', name: 'bag', emoji: '👜' },
      { id: 'belt', name: 'belt', emoji: '👖' },
      { id: 'umbrella', name: 'umbrella', emoji: '☂️' },
      { id: 'backpack', name: 'backpack', emoji: '🎒' },
      { id: 'jacket', name: 'jacket', emoji: '🧥' },
      { id: 'watch', name: 'watch', emoji: '⌚' },
      { id: 'sweater', name: 'sweater', emoji: '🧶' },
    ],
  },
  {
    id: 'body',
    name: 'Body',
    icon: '👋',
    color: '#78909C',
    bgColor: '#ECEFF1',
    words: [
      { id: 'hand', name: 'hand', emoji: '✋' },
      { id: 'eye', name: 'eye', emoji: '👁️' },
      { id: 'ear', name: 'ear', emoji: '👂' },
      { id: 'nose', name: 'nose', emoji: '👃' },
      { id: 'mouth', name: 'mouth', emoji: '👄' },
      { id: 'tooth', name: 'tooth', emoji: '🦷' },
      { id: 'brain', name: 'brain', emoji: '🧠' },
      { id: 'bone', name: 'bone', emoji: '🦴' },
      { id: 'heart', name: 'heart', emoji: '❤️' },
      { id: 'foot', name: 'foot', emoji: '🦶' },
      { id: 'muscle', name: 'muscle', emoji: '💪' },
      { id: 'tongue', name: 'tongue', emoji: '👅' },
      { id: 'neck', name: 'neck', emoji: '🧣' },
      { id: 'shoulder', name: 'shoulder', emoji: '💪' },
      { id: 'knee', name: 'knee', emoji: '🦵' },
      { id: 'elbow', name: 'elbow', emoji: '💪' },
      { id: 'wrist', name: 'wrist', emoji: '✋' },
      { id: 'chin', name: 'chin', emoji: '😊' },
      { id: 'back', name: 'back', emoji: '🔙' },
      { id: 'forehead', name: 'forehead', emoji: '😮' },
    ],
  },
  {
    id: 'insects',
    name: 'Insects',
    icon: '🦋',
    color: '#8D6E63',
    bgColor: '#EFEBE9',
    words: [
      { id: 'butterfly', name: 'butterfly', emoji: '🦋' },
      { id: 'bee', name: 'bee', emoji: '🐝' },
      { id: 'ant', name: 'ant', emoji: '🐜' },
      { id: 'ladybug', name: 'ladybug', emoji: '🐞' },
      { id: 'dragonfly', name: 'dragonfly', emoji: '🪲' },
      { id: 'grasshopper', name: 'grasshopper', emoji: '🦗' },
      { id: 'mosquito', name: 'mosquito', emoji: '🦟' },
      { id: 'spider', name: 'spider', emoji: '🕷️' },
      { id: 'beetle', name: 'beetle', emoji: '🪲' },
      { id: 'caterpillar', name: 'caterpillar', emoji: '🐛' },
      { id: 'fly', name: 'fly', emoji: '🪰' },
      { id: 'moth', name: 'moth', emoji: '🦋' },
      { id: 'wasp', name: 'wasp', emoji: '🐝' },
      { id: 'cricket', name: 'cricket', emoji: '🦗' },
      { id: 'firefly', name: 'firefly', emoji: '✨' },
      { id: 'cockroach', name: 'cockroach', emoji: '🪳' },
      { id: 'mantis', name: 'mantis', emoji: '🦗' },
      { id: 'termite', name: 'termite', emoji: '🐜' },
      { id: 'centipede', name: 'centipede', emoji: '🐛' },
      { id: 'scorpion', name: 'scorpion', emoji: '🦂' },
    ],
  },
  {
    id: 'colors',
    name: 'Colors',
    icon: '🎨',
    color: '#E91E63',
    bgColor: '#FCE4EC',
    words: [
      { id: 'red', name: 'red', emoji: '🔴' },
      { id: 'blue', name: 'blue', emoji: '🔵' },
      { id: 'green', name: 'green', emoji: '🟢' },
      { id: 'yellow', name: 'yellow', emoji: '🟡' },
      { id: 'orange_c', name: 'orange', emoji: '🟠' },
      { id: 'purple', name: 'purple', emoji: '🟣' },
      { id: 'pink', name: 'pink', emoji: '🩷' },
      { id: 'black', name: 'black', emoji: '⬛' },
      { id: 'white', name: 'white', emoji: '⬜' },
      { id: 'brown', name: 'brown', emoji: '🟤' },
      { id: 'gray', name: 'gray', emoji: '🩶' },
      { id: 'gold', name: 'gold', emoji: '🌟' },
      { id: 'silver', name: 'silver', emoji: '⚪' },
      { id: 'turquoise', name: 'turquoise', emoji: '💎' },
      { id: 'indigo', name: 'indigo', emoji: '🫐' },
      { id: 'beige', name: 'beige', emoji: '🏜️' },
      { id: 'navy', name: 'navy', emoji: '🌊' },
      { id: 'coral', name: 'coral', emoji: '🪸' },
      { id: 'mint', name: 'mint', emoji: '🌿' },
      { id: 'maroon', name: 'maroon', emoji: '🍷' },
    ],
  },
  {
    id: 'numbers',
    name: 'Numbers',
    icon: '🔢',
    color: '#1565C0',
    bgColor: '#E3F2FD',
    words: [
      { id: 'one', name: 'one', emoji: '1️⃣' },
      { id: 'two', name: 'two', emoji: '2️⃣' },
      { id: 'three', name: 'three', emoji: '3️⃣' },
      { id: 'four', name: 'four', emoji: '4️⃣' },
      { id: 'five', name: 'five', emoji: '5️⃣' },
      { id: 'six', name: 'six', emoji: '6️⃣' },
      { id: 'seven', name: 'seven', emoji: '7️⃣' },
      { id: 'eight', name: 'eight', emoji: '8️⃣' },
      { id: 'nine', name: 'nine', emoji: '9️⃣' },
      { id: 'ten', name: 'ten', emoji: '🔟' },
      { id: 'eleven', name: 'eleven', emoji: '1️⃣1️⃣' },
      { id: 'twelve', name: 'twelve', emoji: '1️⃣2️⃣' },
      { id: 'thirteen', name: 'thirteen', emoji: '1️⃣3️⃣' },
      { id: 'fourteen', name: 'fourteen', emoji: '1️⃣4️⃣' },
      { id: 'fifteen', name: 'fifteen', emoji: '1️⃣5️⃣' },
      { id: 'sixteen', name: 'sixteen', emoji: '1️⃣6️⃣' },
      { id: 'seventeen', name: 'seventeen', emoji: '1️⃣7️⃣' },
      { id: 'eighteen', name: 'eighteen', emoji: '1️⃣8️⃣' },
      { id: 'nineteen', name: 'nineteen', emoji: '1️⃣9️⃣' },
      { id: 'twenty', name: 'twenty', emoji: '2️⃣0️⃣' },
    ],
  },
]

export function shuffleArray(arr) {
  const copy = [...arr]
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[copy[i], copy[j]] = [copy[j], copy[i]]
  }
  return copy
}

export const BATCH_SIZE = 8
